ALTER TABLE Images ADD COLUMN BitmapPath STRING;
ALTER TABLE ResponsePhotos ADD COLUMN PicturePath STRING;
ALTER TABLE Responses ADD COLUMN ResponsePhoto RESPONSEPHOTO;
ALTER TABLE ResponsePhotos DROP COLUMN Survey;